/* eslint-disable jsx-a11y/anchor-is-valid */
import React from 'react';
import { GetStaticPaths, GetStaticPropsContext } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import ArrowCircleLeftOutlinedIcon from '@mui/icons-material/ArrowCircleLeftOutlined';
import { Typography } from '@mui/material';
import { getAllPostSlugs, getPostData } from '../../libs/posts';
import Layout from '../../components/layouts/Layout';
import styles from '../../styles/Home.module.css';

type PathParams = {
  slug: string;
};

type PageProps = {
  postData: {
    slug: string;
    fileContents: string;
  };
  allPostSlugs: {
    params: {
      slug: string;
    };
  }[];
};

export const getStaticPaths: GetStaticPaths<PathParams> = () => {
  const paths = getAllPostSlugs();

  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps = (
  context: GetStaticPropsContext<{ slug: string }>
) => {
  if (!context || !context.params) throw Error('Data fetch error');
  const postData = getPostData(context.params.slug);
  const allPostSlugs = getAllPostSlugs();

  return {
    props: {
      postData,
      allPostSlugs,
    },
  };
};

const TestingPages: React.FC<PageProps> = ({
  postData,
  allPostSlugs,
}: PageProps) => (
  <div className={styles.container}>
    <Layout allPostSlugs={allPostSlugs}>
      <Head>
        <title>WOVN Test Website on Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <article>
        <div dangerouslySetInnerHTML={{ __html: postData.fileContents }} />
      </article>
      <section>
        <Link href="/">
          <Typography variant="body1">
            <a>
              <ArrowCircleLeftOutlinedIcon />
              Back
            </a>
          </Typography>
        </Link>
      </section>
    </Layout>
  </div>
);

export default TestingPages;
