import { Typography } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import Layout from '../components/layouts/Layout';
import getAllPostSlugs from '../libs/posts';
import styles from '../styles/Home.module.css';

type PageProps = {
  allPostSlugs: {
    params: {
      slug: string;
    };
  }[];
};

const Home: NextPage<PageProps> = ({ allPostSlugs }: PageProps) => (
  <div className={styles.container}>
    <Layout allPostSlugs={allPostSlugs}>
      <Head>
        <title>WOVN Test Website on Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>TOP Page</h2>
      <Typography variant="body1">
        プロジェクトディレクトリ直下の posts ディレクトリに html
        ファイルを作成してコミットすると自動でページをはやしてくれる。
      </Typography>
      <Typography variant="body1">
        WOVN タグは src/components/layouts/Layout.tsx に挿入している。
      </Typography>
      <Typography variant="body1">
        独自言語切替ウィジェットは src/components/layouts/SideBar.tsx
        に。複雑になったらコンポーネントを分ける。
      </Typography>
    </Layout>
  </div>
);

// eslint-disable-next-line @typescript-eslint/require-await
export const getStaticProps = async () => {
  const allPostSlugs = getAllPostSlugs();

  return {
    props: {
      allPostSlugs,
    },
  };
};

export default Home;
