import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import Layout from '../components/layouts/Layout';
import getAllPostSlugs from '../libs/posts';
import styles from '../styles/Home.module.css';

type PageProps = {
  allPostSlugs: {
    params: {
      slug: string;
    };
  }[];
};

const Home: NextPage<PageProps> = ({ allPostSlugs }: PageProps) => (
  <div className={styles.container}>
    <Layout allPostSlugs={allPostSlugs}>
      <Head>
        <title>WOVN Test Website on Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>TOP Page</h2>
      {allPostSlugs.map((value) => (
        <Link href={`/posts/${value.params.slug}`}>{value.params.slug}</Link>
      ))}
    </Layout>
  </div>
);

// eslint-disable-next-line @typescript-eslint/require-await
export const getStaticProps = async () => {
  const allPostSlugs = getAllPostSlugs();

  return {
    props: {
      allPostSlugs,
    },
  };
};

export default Home;
