name: deploy
on: 
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: killinsun.com
          username: centos
          port: 22
          key: ${{ secrets.SSH_KEY }}
          script: |
            /bin/bash
            cd /usr/local/share/docker-compose/wovn-testing-site
            git pull
            docker-compose restart
