name: deploy
on: 
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Deploy
        uses: fifsky/ssh-action@master
        with:
          host: killinsun.com
          user: centos
          port: 22
          key: ${{ secrets.SSH_KEY }}
          command: |
            /bin/bash
            echo 'hello!'
