name: deploy
on: 
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: fifsky/ssh-action@master
        env:
          NVM_DIR: "~/.nvm"
        with:
          host: killinsun.com
          user: centos
          port: 22
          key: ${{ secrets.SSH_KEY }}
          command: |
            cd /usr/local/share/docker-compose/wovn-testing-site
            git pull origin master
            docker-compose restart



